name: enum_string_value_lib
description: Now your enum classes have String values!!
version: 0.0.1
homepage: https://github.com/kikuchy/enum_string_value
author: kikuchy <kikuchy.h@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
