name: example
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: kikuchy <kikuchy.h@gmail.com>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  enum_string_value_lib: ^0.0.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.7.1
  enum_string_value_generator:
    path: ../enum_string_value_generator
